# Generated by Django 2.2.1 on 2019-11-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='itemID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
