# Generated by Django 2.2.1 on 2019-11-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191129_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='userID',
            new_name='publisher',
        ),
    ]
