# Generated by Django 2.2.1 on 2019-11-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191129_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
