# Generated by Django 2.2.1 on 2019-11-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191129_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
