# Generated by Django 2.2.1 on 2019-11-29 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
    ]
