# Generated by Django 3.0 on 2020-01-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='isCrashed',
            field=models.BooleanField(default=False),
        ),
    ]
