# Generated by Django 3.0 on 2020-02-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_iscrashed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gsLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='pdfLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoFile360',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoFile480',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoFile720',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
